### ISSUE TITLE
Custom Prefix Implementation

### ISSUE THREAD

**Issue by CaffeineDuck** [FalseDev/Tech-Struck#13]

**Comment by xFGhoul** [comment]
@FalseDev If you want I can go ahead and do this (create a PR) if you're not already doing it

**Comment by FalseDev** [comment]
> @FalseDev If you want I can go ahead and do this (create a PR) if you're not already doing it

I'm currently working on this, almost done as well

**Comment by FalseDev** [comment]
Fixed in commits 0914c25599fda90e906918bb9833fcda34d2b42f and 02b0ff3f86c9dc698a61f33d91cfe970d8572435
