### ISSUE TITLE
RTFM Command for the docs!

### ISSUE THREAD

**Issue by CaffeineDuck** [FalseDev/Tech-Struck#14]
## An RTFM command to search through documentation
 - [x] Working version
 - [x] Add a bunch of popular python modules
 - [x] Edge cases, error handling
 - [x] Command to add modules in runtime (maintainer only)
 - [x] RTFM for Mkdocs based docs see [this](https://github.com/mkdocstrings/mkdocstrings/issues/251)
 - [ ] RTFM for JSDoc based docs see [this](https://github.com/jsdoc/jsdoc/issues/1896)

**Comment by WhoIsConch** [comment]
Wow amazing

**Comment by Thuliumify** [comment]
monke

**Comment by FalseDev** [comment]
## Current selection of modules for RTFM command

```py
{
 "aiohttp": "https://docs.aiohttp.org/en/stable",
 "aiosqlite": "https://aiosqlite.omnilib.dev/en/latest",
 "apraw": "https://apraw.readthedocs.io/en/latest",
 "asyncpg": "https://magicstack.github.io/asyncpg/current",
 "discord.py": "https://discordpy.readthedocs.io/en/latest",
 "flask": "https://flask.palletsprojects.com/en/1.1.x",
 "imageio": "https://imageio.readthedocs.io/en/stable",
 "matplotlib": "https://matplotlib.org/stable",
 "numpy": "https://numpy.readthedocs.io/en/latest",
 "pandas": "https://pandas.pydata.org/docs",
 "pillow": "https://pillow.readthedocs.io/en/stable",
 "praw": "https://praw.readthedocs.io/en/latest",
 "pygame": "https://www.pygame.org/docs",
 "python": "https://docs.python.org/3",
 "requests": "https://requests.readthedocs.io/en/master",
 "seaborn": "https://seaborn.pydata.org",
 "simplejson": "https://simplejson.readthedocs.io/en/latest",
 "sqlalchemy": "https://docs.sqlalchemy.org/en/14",
 "wikipedia": "https://wikipedia.readthedocs.io/en/latest"
}
```

**Comment by RKNpy** [comment]
Exclusive beer 🍻 when ?

**Comment by Thuliumitation** [comment]
{
  "matplotlib": "https://matplotlib.org/contents.html",
  "beautifulsoup4": "https://readthedocs.org/projects/beautiful-soup-4/",
  "praw": "https://praw.readthedocs.io/",
  "pydictionary": "https://pypi.org/project/PyDictionary/"
}
Gonna add more in the future :)

**Comment by FalseDev** [comment]
> {
>   "matplotlib": "https://matplotlib.org/contents.html",
>   "beautifulsoup4": "https://readthedocs.org/projects/beautiful-soup-4/",
>   "praw": "https://praw.readthedocs.io/",
>   "pydictionary": "https://pypi.org/project/PyDictionary/"
> }
> Gonna add more in the future :)

Great suggestions! I'll update my listing soon!

**Comment by shadow286** [comment]
pog

**Comment by Da4kek** [comment]
{
"seaborn" : "https://pypi.org/project/seaborn/"
"keras": "https://pypi.org/project/Keras/"
"pillow": "https://pypi.org/project/Pillow/"
"discord" : "https://pypi.org/project/discord.py/"
"simple-json": "https://pypi.org/project/simplejson/"
"tensorflow" : "https://pypi.org/project/tensorflow/"
}
There is a lot more in future :)

**Comment by FalseDev** [comment]
@Thuliumify @The-DarK-os I've added your suggestions to [this](https://github.com/FalseDev/Tech-Struck/issues/14#issuecomment-791964769) comment, note that **only compatible modules** have been added.

These newer ones are pushed in commits a99ea29d59d5a4e63b52289bf62a292ca0d44062 and 8501730ed03f28eed8b7696109e23409c2c1c0f5
