### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by FalseDev** [FalseDev/Tech-Struck#16]
The readme currently states Tech Struck as a server specific custom discord bot which is outdated info.

Currently Tech Struck has become a multi server tech community bot

 - [ ] Info
 - [ ] Badges
 - [ ] Partnering
 - [ ] Contributing

**Comment by FalseDev** [comment]
@ProGamer368 has taken this

**Comment by FalseDev** [comment]
Has been updated by @Nirlep5252

**Comment by Nirlep5252** [comment]
uwu
