### ISSUE TITLE
Github commands accessible by pinging the linked user!

### ISSUE THREAD

**Issue by CaffeineDuck** [FalseDev/Tech-Struck#20]
Make it so that if the user has linked his/her github acc with the bot, his/her stats and data can be obtained by mentioning the user!

Example: 
Command: .githubstats @GayVodka#6969
Should return: Stats of my linked github account (Samrid-Pandit)

**Comment by FalseDev** [comment]
While this works, this isn't a good idea, it's a very bad idea, and in a way is also misuse. We cannot use a user's token upon another user's request.

Hence I'm closing this issue.

**Comment by CaffeineDuck** [comment]
I mean, you are right, but just for the github stats and ghlangs maybe we can have it, cause the info is publicly available? maybe?
Or we could just store the github username in the db linked to the user?

**Comment by FalseDev** [comment]
Storing the username in the database works, but is kinda unnecessary as we would rather just allow users to use a Github username, using the token to retrieve and store the when it's not on behalf is also possibly against it's usage terms

Finally, it's also error prone if the user changes their username for example

**Comment by CaffeineDuck** [comment]
Hmm, yea you are right. Lets end it at that.
