### ISSUE TITLE
Allow gist creation using message ids as well

### ISSUE THREAD

**Issue by Tanishquasar** [FalseDev/Tech-Struck#25]
## Current Condition
At this moment, if someone attempts gist creation via replying to a message containing a file with `.creategist`, it succeeds.

## Request
It should also be able to create gist if someone types `.creategist [message_id]` which will be overall functional.

**Comment by FalseDev** [comment]
But isn't replying to the message actually simpler than copying and pasting and ID?

Also it'll only make the files parsing regex more complex, so I guess this won't be worked on

**Comment by Tanishquasar** [comment]
Seems sensible enough.
