### ISSUE TITLE
Beerparty Randomness

### ISSUE THREAD

**Issue by StarTwi** [FalseDev/Tech-Struck#29]
Make the beerparty command return random names of the users reacted to the message

**Comment by FalseDev** [comment]
Can you explain please?

**Comment by StarTwi** [comment]
Take and example-
I, You and the third person react with 🍻 . Now I react first, you react second, the third person reacts after you.
Now when the bot sends the message it will send it like `Glim, FalseDev and Third Person are enjoying a lovely beer together`.
I ask to make it like it returns the names of the people randomly for example- `Glim,Thier Person and False are enjoying lovely beer together` like just return the names of the users randomly

**Comment by FalseDev** [comment]
It is already kinda random, discord api returns the user list in possibly a random way
