### ISSUE TITLE
Marking a help channel as "Occupied" and "Available"

### ISSUE THREAD

**Issue by Tanishquasar** [FalseDev/Tech-Struck#33]
A future feature should allow users to ask for help in any channel i.e. marked as **"Available"**. As soon as they ask for help, the bot will ask for their confirmation and then mark the respective channel as **"Occupied"**. The message asking for help will be pinned automatically.

If the member has received satisfactory help, they can close the channel by typing a command and it will again mark the channel as **"Available"** after a certain cooldown. This will also remove the respective pins.

- [ ] Mark default help channels to "Available"
- [ ] Ask for confirmation on message
- [ ] Pin message on affirmative reply
- [ ] A command to close the channel and delete the pin

**Comment by FalseDev** [comment]
This will be a feature on the rewrite
