### ISSUE TITLE
Github Stats and Most Used Langs

### ISSUE THREAD

**Issue by ghost** [FalseDev/Tech-Struck#4]
So, I saw your github thing which is pog. Now if you can extract the username of the user or take it as an argument. Use this library: https://github.com/anuraghazra/github-readme-stats to basically make a command which tells you someones' stats and most used langs. 

Additionally try to create an embed and set_image with this image. And btw you can take in a theme argument!

**Comment by FalseDev** [comment]
@NightZan999 Thank you suggesting this!

This has been undertaken by @CodeWithSwastik and should be added within a couple days max.
