### ISSUE TITLE
Fucking ass punctuation

### ISSUE THREAD

**Issue by WhoIsConch** [FalseDev/Tech-Struck#41]
The beer command doesn't add a fucking space after the colon and if you don't fix it ill rip out **_your_** colon

![Screenshot_20210327-115452_Discord.jpg](https://user-images.githubusercontent.com/69608854/112726543-643fcf80-8ef4-11eb-8ae7-7012c71b8ab2.jpg)

**Comment by Dorukyum** [comment]
I noticed the fix was wrong, the correct fix is adding a space after the ":" in line 105.
