### ISSUE TITLE
GitHub command suggestion

### ISSUE THREAD

**Issue by StarTwi** [FalseDev/Tech-Struck#5]
Make a command to check someone's GitHub stats just like finding a user profile smh and DO NOT FORGET TO INCLUDE THEIR PFP THERE Imao :FalseFacePalmLaugh: <br>

**Comment by FalseDev** [comment]
Lmao this is a clone of #4

**Comment by StarTwi** [comment]
;-; brb killing the og

**Comment by StarTwi** [comment]
![image](https://user-images.githubusercontent.com/71965763/109008362-4142b580-76d3-11eb-93ab-5c81bc64b137.png)
:starlightwtfbro: was just gonna close this one Imao

**Comment by ghost** [comment]
> Make a command to check someone's GitHub stats just like finding a user profile smh and DO NOT FORGET TO INCLUDE THEIR PFP THERE Imao :FalseFacePalmLaugh:

bruh ur copy pasting issues to get commits? -_-

**Comment by CodeWithSwastik** [comment]
Closing because it is a duplicate of #4
